#!/bin/sh

for FILE in "$@"
do
    case "${FILE}" in
        *.bak)
            cp --interactive --verbose -- "${FILE}" "${FILE%.bak}"
            ;;
        *)
            mv --verbose -- "${FILE}.bak" "${FILE}"
            ;;
    esac
done
