#!/bin/sh

world="/var/lib/portage/world"

[ -f "${world}" ] || exit

while read -r line; do
    if [ -n "$(qdepends --quiet --query "${line}")" ]; then
        echo "${line}"
    fi
done <"${world}"
