#!/bin/sh

for id in $(docker ps -q | awk '{print $1}')
do
    ip=$(docker inspect --format="{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}" "$id")
    name=$(docker ps | grep "$id" | awk '{print $NF}')

    printf "%s %s\n" "$ip" "$name"
done
