#!/bin/sh

if ! command -v xsetroot >/dev/null 2>&1 \
&& ! command -v pgrep >/dev/null 2>&1
then
    exit
fi

while :
do
    OUT=" "
    if [ "${HOST}" != "sava" ]
        BAT="/sys/class/power_supply/BAT0"
        if [ "$(cat ${BAT}/present)" -eq 1 ]
        then
            OUT="${OUT}\`$(cat ${BAT}/capacity)%\` "
        fi
    fi
    OUT="${OUT}$(date +%F\ %R) "

    xsetroot -name "${OUT}" || \
        exit

    sleep 10
done
