#!/bin/sh

if ! command -v xsetroot >/dev/null 2>&1 \
&& ! command -v pgrep >/dev/null 2>&1
then
    exit
fi

while :
do
    out=" "
    if [ "${HOST}" != "sava" ]
    then
        bat="/sys/class/power_supply/BAT0"
        if [ "$(cat ${bat}/present)" -eq 1 ]
        then
            out="${out}\`$(cat ${bat}/capacity)%' "
        fi
    fi
    out="${out}$(date +%F\ %R) "

    xsetroot -name "${out}" || \
        exit

    sleep 10
done
