#!/bin/sh

to_rm="
    ${HOME}/.cache
    ${HOME}/.ccls-cache
    ${HOME}/.gdb_history
    ${HOME}/.nvimlog
    ${HOME}/.rnd
    ${HOME}/.viminfo
    ${HOME}/.wget-hsts
    ${HOME}/VideoDecodeStats
    ${HOME}/databases-incognito
    ${HOME}/pgadmin.log
    ${HOME}/shared_proto_db
"

rm_existing() {
    if [ -f "${1}" -o -d "${1}" ]; then
        rm -rf "${1}" || return
    fi
}

for i in ${to_rm}; do
    rm_existing "${i}" || exit
done
