#!/bin/sh

MPD_CONF="${XDG_CONFIG_HOME}/mpd/mpd.conf"
MPDSCRIBBLE_CONF="${XDG_CONFIG_HOME}/mpdscribble.conf"

if command -v mpd >/dev/null 2>&1 \
&& [ -f "${MPD_CONF}" ] \
&& [ ! -f "/tmp/mpd.pid" ]
then
    mpd "${MPD_CONF}" || exit $?

    if command -v mpdscribble >/dev/null 2>&1 \
    && [ -f "${MPDSCRIBBLE_CONF}" ] \
    && [ -f "/tmp/mpd.pid" ] \
    && [ ! -f "/tmp/mpdscribble.pid" ]
    then
        mpdscribble --conf "${MPDSCRIBBLE_CONF}"
    fi
fi

unset MPD_CONF
unset MPDSCRIBBLE_CONF
