#!/bin/bash

mudir="/media/marisa/music"
mtpdir="/media/marisa/syncthing/music"

for i in "${mudir}/${1}"/*
do
    cd "${i}" || exit 1
    name="$(pwd | sed -e 's/\/media\/marisa\/music\///')"
    mkdir -p "${mtpdir}/${target}"
    if compgen -G ./*.mp3
    then
        cp -r ./*.mp3 "${mtpdir}/${target}"
    elif compgen -G ./*.flac
    then
        flac2ogg
        while [ "$(pgrep perl)" ]
        do
            sleep 1
        done
        mv ./*.ogg "${mtpdir}/${target}"
    fi
    cd "${mudir}" || exit 1
done
