#!/usr/bin/env bash

IMGPATH="$HOME/emulation/windows/guest.qcow2"
SMBPATH="$HOME/shared"

qemu-system-x86_64 \
    -machine "type=pc-q35-2.9,accel=kvm,vmport=off,dump-guest-core=off,mem-merge=off,nvdimm=off" \
    -cpu "host,hv_relaxed,hv_spinlocks=0x1fff,hv_vapic,hv_time" \
    -accel "kvm" \
    -m "size=2048" \
    -k "en-us" \
    -usbdevice "tablet" \
    -drive "file=$IMGPATH,format=qcow2" \
    -name "windows-7" \
    -display "sdl,frame=off,window_close=off" \
    -sdl \
    -net "nic" \
    -net "user,smb=$SMBPATH" \
    -enable-kvm \
    -daemonize
    "$@"
