#!/bin/bash

DOWNDIR="$HOME/downloads"
SONGDIR="$HOME/.wine/drive_c/users/$USER/Local Settings/Application Data/osu!/Songs"

if [ -d "$DOWNDIR" ]
then
    if [ -d "$SONGDIR" ]
    then
        if (shopt -s nullglob dotglob
            f=("$DOWNDIR"/*.osz)
            ((! ${#f[@]})))
        then
            echo -e "osu-getmaps: no beatmaps found in \"$DOWNDIR\", aborting"
            exit 1
        else
            for MAP in "$DOWNDIR"/*.osz
            do
                mv --verbose --update --force "$MAP" "$SONGDIR"
            done
        fi

        shopt -u nullglob dotglob
    else
        echo -e "osu-getmaps: directory \"$SONGDIR\" does not exist, aborting"
        exit 1
    fi
else
    echo -e "osu-getmaps: directory \"$DOWNDIR\" does not exist, aborting"
    exit 1
fi
