#!/bin/bash

PIC="$HOME/pictures/wallpapers/mill-blur.png"
SONGDIR="$HOME/.wine/drive_c/users/$USER/Local Settings/Application Data/osu!/Songs"

[ -d "$SONGDIR/Failed" ] && \
    rm -rf "$SONGDIR/Failed"

for SET in "$SONGDIR"/*
do
    if [ -d "$SET" ]
    then
        for DIFF in "$SET"/*.osu
        do
            IMAGE="$( \
                while IFS= read -r line; \
                do \
                    regex='^0,0,"([^"]*)"'; \
                    [[ $line =~ $regex ]] && \
                        echo "${BASH_REMATCH[1]}"; \
                done < "$DIFF")"

            echo -e "osu-chbg: Processing: \033[0;32m\"${SET#*'Songs/'}\"\033[0m"

            if [ -f "$SET/$IMAGE" ]
            then
                [ ! -f "$SET/.$IMAGE.bak" ] && \
                    cp --no-clobber "$SET/$IMAGE" "$SET/.$IMAGE.bak"
                cp "$PIC" "$SET/$IMAGE"
            fi
        done
    fi
done
