#!/usr/bin/env bash

FMASK=$(umask -S | sed 's/x//g')
DMASK=$(umask -S)

for i
do
    find "$i" -exec chown -R "$UID:$GID" {} \;
    find "$i" -type d -exec chmod "$DMASK" {} \;
    find "$i" -type f -exec chmod "$FMASK" {} \;
done
