#!/usr/bin/awk -f

BEGIN
{
    if (begin == "")
        begin ="/\\*"
    if (end == "")
        end ="\\*/"
}

{
    while (match($0, begin))
    {
        before = substr($0, 1, RSTART - 1)
        $0 = substr($0, RSTART)
        printf("%s", before)

        while (!match($0, end))
            getline

        $0 = substr($0, RSTART + length(end) - 1)
    }
    print
}
