#!/bin/sh

for i in st urxvtc urxvt rxvt xterm
do
    if [ "${i}" = "urxvtc" ] \
    && ! pgrep urxvtd >/dev/null 2>&1
    then
        continue
    fi

    command -v "$i" >/dev/null 2>&1 && \
        exec "$i" "$@"
done
